### ISSUE TITLE
Cannot update visidata to 2.2 due to SHA256 mismatch

### ISSUE THREAD

**Issue by gbstan** [saulpw/homebrew-vd#11]
When trying to update visidata with brew reinstall visidata to get the latest version, v2.2, the following error occurs:

Error: SHA256 mismatch
Expected: 667db2f91f3b375fb8ccff114c65ea913b01d67be608cd973539921fbbf7a3e0
  Actual: ddd6fa8db87a04966df7bfcf05d3d04a4346db170f08f51b7fcdaf9ca985c06a
    File: /Users/[EDITED]/Library/Caches/Homebrew/downloads/a43bebaf562faff7126fab9917e1f91c21dc74cabcd8a9f470ed4ed97bc82c41--visidata-2.1.1.tar.gz
To retry an incomplete download, remove the file above.

I have tried to remove the file as indicated above but this still doesn't solve the problem.

**Comment by anjakefala** [comment]
Thanks for letting me know @gbstan!

It was pulling down the wrong file. It should work now.

**Comment by gbstan** [comment]
Still not working unfortunately:

curl: (22) The requested URL returned error: 404
Error: Failed to download resource "visidata"
Download failed: https://files.pythonhosted.org/packages/1f/dd/b94bcea6906ae5376e65fcf7a7dec3966ec8d8a9fbeb7279ac627d4bc187/visidata-2.2.tar.gz

**Comment by anjakefala** [comment]
Blech, thanks! @gbstan Does it work now?

**Comment by gbstan** [comment]
Yes, this works!
